unbind r 
bind r source-file ~/.tmux.conf

set -g prefix C-Space
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g status-left-length 30

set -g status-left " [ #S ]  "
set -g status-right '  #(TZ="Asia/Taipei" date +"%%H:%%M %%b-%%d-%%y")  '
set -g window-status-format "#I:#W "
set -g window-status-current-format "#[bold]#I:#W* "
set -g renumber-windows on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# status bar theme
# set -g @plugin 'catppuccin/tmux'
# set -g @catppuccin_flavour 'frappe' # or latte, macchiato, mocha
set -g @plugin 'seebi/tmux-colors-solarized'
set -g @colors-solarized 'dark'

# hotz' conf
# set -g status-bg colour234
# set -g status-fg colour137
# setw -g window-status-current-format ' #I#[fg=colour250]:#[fg=colour255]#W#[fg=colour50]#F '
# setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '

# true colours support
# set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides ",xterm-256color:Tc"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
# underscore colours - needs tmux-3.0
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
